"""
Live ANC Simulation Visualization.

Runs a trained PIRL-ANC agent in the simulated environment and produces
a real-time 3-panel matplotlib animation showing:

  Panel 1 — Measured Noise:  Target pressure signal at the quiet-zone location.
  Panel 2 — Agent Output:    Anti-noise waveform generated by the RL controller,
                             with per-speaker amplitude and phase annotations.
  Panel 3 — Net Sound (dB):  Residual sound pressure level at the target point
                             after superposition of noise + anti-noise.

Usage:
    python -m pirl_anc.sim.live_demo
    python -m pirl_anc.sim.live_demo --checkpoint pirl_anc/checkpoints/pretrain_agent.pt
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Optional

import matplotlib
matplotlib.use("TkAgg")  # interactive backend for live window

import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

from ..agent.sac_agent import PIRLSACAgent
from ..common import select_device
from ..config import load_config
from ..envs.anc_env import ANCEnvironment
from ..physics.wave_penalty import PhysicsPenalty


# ---------------------------------------------------------------------------
# Colour palette — dark-mode inspired
# ---------------------------------------------------------------------------
BG_DARK   = "#0D1117"
BG_PANEL  = "#161B22"
NOISE_CLR = "#FF6B6B"   # coral red
ANTI_CLR  = "#4ECDC4"   # teal
NET_CLR   = "#FFE66D"   # warm yellow
GRID_CLR  = "#30363D"
TEXT_CLR  = "#C9D1D9"
ACCENT    = "#58A6FF"


def _db_spl(rms: float, p_ref: float = 2e-5) -> float:
    """Convert RMS pressure to dB SPL (re 20 µPa)."""
    if rms < 1e-12:
        return -120.0
    return 20.0 * np.log10(rms / p_ref)


def run_live_demo(
    checkpoint: str | Path | None = None,
    cfg_path: str | Path | None = None,
    interval_ms: int = 80,
    save_path: str | Path | None = None,
) -> None:
    """Launch the live 3-panel ANC visualization.

    Args:
        checkpoint: Path to a trained agent checkpoint. If None, the agent
                    uses random exploration (useful for demonstrating the
                    uncontrolled baseline).
        cfg_path:   Optional YAML config override.
        interval_ms: Milliseconds between animation frames.
        save_path:  If set, save the animation as a GIF/MP4 instead of
                    displaying it interactively.
    """
    # ------------------------------------------------------------------ setup
    cfg = load_config(Path(cfg_path) if cfg_path else None)
    device = select_device()

    env = ANCEnvironment(config_path=cfg_path)
    phys = PhysicsPenalty(lambda_p=cfg.physics.lambda_p)
    state_dim = env.observation_space.shape[0]
    action_dim = env.action_space.shape[0]

    agent = PIRLSACAgent(
        state_dim, action_dim, phys,
        lr=cfg.agent.learning_rate,
        gamma=cfg.agent.gamma,
        tau=cfg.agent.tau,
        device=str(device),
    )

    has_checkpoint = False
    if checkpoint is not None:
        ckpt = Path(checkpoint)
        if ckpt.exists():
            agent.load(ckpt)
            has_checkpoint = True
            print(f"Loaded checkpoint: {ckpt}")
        else:
            print(f"Checkpoint not found: {ckpt} — running with untrained agent")
    else:
        print("No checkpoint supplied — running with untrained (random) agent")

    # --------------------------------------------------------- episode reset
    obs, _ = env.reset()
    fs = env.fs
    window = env.window
    hop = env.hop
    n_speakers = env.n_speakers

    # Pre-compute the full target signal for the top panel
    target_full = env._target_signal.copy()
    total_samples = len(target_full)
    time_axis_full = np.arange(total_samples) / fs

    # Storage for per-step data
    step_times: list[float] = []          # centre time of each window
    noise_rms_db: list[float] = []        # noise dB per step
    antinoise_rms_db: list[float] = []    # anti-noise dB per step
    net_rms_db: list[float] = []          # residual dB per step
    speaker_amps: list[list[float]] = []  # per-speaker amplitude history
    speaker_phases: list[list[float]] = []

    # Waveform buffers for the current step (updated each frame)
    current_noise_window = np.zeros(window, dtype=np.float32)
    current_anti_window = np.zeros(window, dtype=np.float32)
    current_residual_window = np.zeros(window, dtype=np.float32)
    current_t_window = np.arange(window) / fs

    # --------------------------------------------------------- figure setup
    fig, (ax_noise, ax_anti, ax_db) = plt.subplots(
        3, 1, figsize=(14, 9),
        gridspec_kw={"height_ratios": [1, 1, 1.2], "hspace": 0.35},
    )
    fig.patch.set_facecolor(BG_DARK)

    for ax in (ax_noise, ax_anti, ax_db):
        ax.set_facecolor(BG_PANEL)
        ax.tick_params(colors=TEXT_CLR, labelsize=9)
        ax.xaxis.label.set_color(TEXT_CLR)
        ax.yaxis.label.set_color(TEXT_CLR)
        ax.title.set_color(TEXT_CLR)
        for spine in ax.spines.values():
            spine.set_color(GRID_CLR)
        ax.grid(True, color=GRID_CLR, alpha=0.4, linewidth=0.5)

    # Panel 1 — Measured Noise
    ax_noise.set_title("Measured Noise at Target Location", fontsize=12,
                       fontweight="bold", pad=8)
    ax_noise.set_xlabel("Time (s)")
    ax_noise.set_ylabel("Pressure (Pa)")
    line_noise, = ax_noise.plot([], [], color=NOISE_CLR, linewidth=0.8,
                                alpha=0.9, label="Noise")
    noise_patch = ax_noise.axvspan(0, 0, alpha=0.15, color=NOISE_CLR)
    ax_noise.legend(loc="upper right", fontsize=8, facecolor=BG_PANEL,
                    edgecolor=GRID_CLR, labelcolor=TEXT_CLR)

    # Plot the full target waveform as faded background
    ax_noise.plot(time_axis_full, target_full, color=NOISE_CLR, alpha=0.15,
                  linewidth=0.3)
    y_max_noise = max(np.abs(target_full).max() * 1.1, 0.01)
    ax_noise.set_xlim(0, time_axis_full[-1])
    ax_noise.set_ylim(-y_max_noise, y_max_noise)

    # Panel 2 — Agent Anti-Noise
    ax_anti.set_title("RL Agent Anti-Noise Output", fontsize=12,
                      fontweight="bold", pad=8)
    ax_anti.set_xlabel("Time within Window (s)")
    ax_anti.set_ylabel("Pressure (Pa)")
    line_anti, = ax_anti.plot([], [], color=ANTI_CLR, linewidth=1.2,
                              alpha=0.9, label="Anti-noise")
    line_residual_wave, = ax_anti.plot([], [], color=NET_CLR, linewidth=0.8,
                                       alpha=0.6, label="Residual")
    ax_anti.set_xlim(0, window / fs)
    ax_anti.set_ylim(-y_max_noise, y_max_noise)
    ax_anti.legend(loc="upper right", fontsize=8, facecolor=BG_PANEL,
                   edgecolor=GRID_CLR, labelcolor=TEXT_CLR)
    # Text annotation for speaker params
    speaker_text = ax_anti.text(
        0.02, 0.92, "", transform=ax_anti.transAxes,
        fontsize=8, fontfamily="monospace", color=ACCENT,
        verticalalignment="top",
        bbox=dict(boxstyle="round,pad=0.3", facecolor=BG_DARK, alpha=0.8,
                  edgecolor=GRID_CLR),
    )

    # Panel 3 — Net Sound dB
    ax_db.set_title("Sound Pressure Level at Target (dB SPL)", fontsize=12,
                    fontweight="bold", pad=8)
    ax_db.set_xlabel("Time (s)")
    ax_db.set_ylabel("SPL (dB re 20 µPa)")
    line_noise_db, = ax_db.plot([], [], color=NOISE_CLR, linewidth=1.5,
                                alpha=0.8, label="Noise only", linestyle="--")
    line_net_db, = ax_db.plot([], [], color=NET_CLR, linewidth=2.0,
                              alpha=0.9, label="After ANC")
    line_anti_db, = ax_db.plot([], [], color=ANTI_CLR, linewidth=1.0,
                               alpha=0.5, label="Anti-noise", linestyle=":")
    ax_db.legend(loc="upper right", fontsize=8, facecolor=BG_PANEL,
                 edgecolor=GRID_CLR, labelcolor=TEXT_CLR)

    # Status text
    status_text = fig.text(
        0.02, 0.01,
        "PIRL-ANC Live Simulation" + (" — Trained Agent" if has_checkpoint else " — Untrained (Random)"),
        fontsize=9, color=ACCENT, fontfamily="monospace",
    )
    step_counter = fig.text(
        0.98, 0.01, "Step 0 / ?", fontsize=9, color=TEXT_CLR,
        fontfamily="monospace", ha="right",
    )
    reduction_text = fig.text(
        0.50, 0.01, "", fontsize=10, color=NET_CLR,
        fontweight="bold", fontfamily="monospace", ha="center",
    )

    fig.suptitle(
        "Physics-Informed RL — Active Noise Cancellation",
        fontsize=14, fontweight="bold", color=TEXT_CLR, y=0.98,
    )

    # --------------------------------------------------------- animation logic
    episode_done = False
    current_obs = obs

    def _step_env(frame_idx: int) -> None:
        """Execute one environment step and store results."""
        nonlocal current_obs, episode_done
        nonlocal current_noise_window, current_anti_window, current_residual_window

        if episode_done:
            return

        # Agent selects action
        action = agent.select_action(current_obs, mode="sim", explore=False)
        action_raw = np.asarray(action, dtype=np.float32).copy()

        # Rescale (same logic as env.step) so we can visualize the anti-noise
        low = env.action_space.low
        high = env.action_space.high
        action_rescaled = low + (action_raw + 1.0) * 0.5 * (high - low)
        action_rescaled = np.clip(action_rescaled, low, high)

        # Extract per-speaker params
        amps = []
        phases = []
        for i in range(n_speakers):
            amps.append(float(action_rescaled[2 * i]))
            phases.append(float(action_rescaled[2 * i + 1]))
        speaker_amps.append(amps)
        speaker_phases.append(phases)

        # Get the noise window BEFORE stepping
        step_idx = env._step_idx
        start = step_idx * hop
        end = start + window
        actual_end = min(end, total_samples)
        noise_win = target_full[start:actual_end]
        if len(noise_win) < window:
            noise_win = np.pad(noise_win, (0, window - len(noise_win)))

        # Build anti-noise from rescaled action (mirrors env.step logic)
        t_arr = np.arange(window, dtype=np.float32) / fs
        anti_win = np.zeros(window, dtype=np.float32)
        for i in range(n_speakers):
            anti_win += amps[i] * np.sin(2.0 * np.pi * 440.0 * t_arr + phases[i])

        residual_win = noise_win[:len(anti_win)] + anti_win[:len(noise_win)]

        # Store waveforms
        current_noise_window = noise_win
        current_anti_window = anti_win
        current_residual_window = residual_win
        current_t_window[:] = np.arange(window) / fs

        # Compute dB values
        noise_rms = float(np.sqrt(np.mean(noise_win ** 2)))
        anti_rms = float(np.sqrt(np.mean(anti_win ** 2)))
        net_rms = float(np.sqrt(np.mean(residual_win ** 2)))

        centre_time = (start + window / 2) / fs
        step_times.append(centre_time)
        noise_rms_db.append(_db_spl(noise_rms))
        antinoise_rms_db.append(_db_spl(anti_rms))
        net_rms_db.append(_db_spl(net_rms))

        # Actually step the environment
        next_obs, reward, term, trunc, info = env.step(action)
        current_obs = next_obs
        if term or trunc:
            episode_done = True

    def _update(frame_idx: int) -> list:
        """Animation callback — step env + update plots."""
        _step_env(frame_idx)

        if len(step_times) == 0:
            return []

        # Panel 1 — highlight current window on full signal
        step_idx = max(env._step_idx - 1, 0)
        start = step_idx * hop
        end = min(start + window, total_samples)
        win_slice = slice(start, end)
        line_noise.set_data(time_axis_full[win_slice], target_full[win_slice])

        # Panel 2 — anti-noise and residual waveforms
        t_win = current_t_window[:len(current_anti_window)]
        line_anti.set_data(t_win, current_anti_window)
        line_residual_wave.set_data(t_win[:len(current_residual_window)],
                                    current_residual_window)

        # Speaker annotation
        if speaker_amps:
            lines = []
            for i in range(n_speakers):
                a = speaker_amps[-1][i]
                p = speaker_phases[-1][i]
                lines.append(f"Spk{i+1}: A={a:.3f}  φ={p:.2f} rad")
            speaker_text.set_text("\n".join(lines))

        # Panel 3 — dB plot
        t_arr = np.array(step_times)
        line_noise_db.set_data(t_arr, noise_rms_db)
        line_net_db.set_data(t_arr, net_rms_db)
        line_anti_db.set_data(t_arr, antinoise_rms_db)

        # Auto-scale dB y-axis
        all_db = noise_rms_db + net_rms_db + antinoise_rms_db
        if all_db:
            db_min = max(min(all_db) - 5, -20)
            db_max = max(all_db) + 5
            ax_db.set_xlim(0, max(t_arr[-1] * 1.05, 0.1))
            ax_db.set_ylim(db_min, db_max)

        # Status texts
        step_counter.set_text(
            f"Step {len(step_times)} / {env.episode_len}"
            + ("  ✓ DONE" if episode_done else ""),
        )

        # Noise reduction metric
        if len(noise_rms_db) > 0 and len(net_rms_db) > 0:
            avg_noise = np.mean(noise_rms_db[-10:])
            avg_net = np.mean(net_rms_db[-10:])
            reduction = avg_noise - avg_net
            reduction_text.set_text(
                f"Noise Reduction: {reduction:+.1f} dB"
                + (f"  (last 10 steps)" if len(noise_rms_db) > 10 else ""),
            )

        return [line_noise, line_anti, line_residual_wave,
                line_noise_db, line_net_db, line_anti_db,
                speaker_text, step_counter, reduction_text]

    max_frames = env.episode_len + 5  # a few extra for the done state
    anim = animation.FuncAnimation(
        fig,
        _update,
        frames=max_frames,
        interval=interval_ms,
        blit=False,
        repeat=False,
    )

    if save_path is not None:
        save_p = Path(save_path)
        save_p.parent.mkdir(parents=True, exist_ok=True)
        if save_p.suffix == ".gif":
            anim.save(str(save_p), writer="pillow", fps=1000 // interval_ms)
        else:
            anim.save(str(save_p), writer="ffmpeg", fps=1000 // interval_ms)
        print(f"Animation saved to {save_p}")
    else:
        plt.show()

    # --------------------------------------------------------- summary stats
    if noise_rms_db and net_rms_db:
        avg_noise_db = np.mean(noise_rms_db)
        avg_net_db = np.mean(net_rms_db)
        peak_noise_db = max(noise_rms_db)
        peak_net_db = max(net_rms_db)
        print(f"\n{'=' * 50}")
        print(f"  Simulation Summary ({len(step_times)} steps)")
        print(f"{'=' * 50}")
        print(f"  Avg noise SPL:        {avg_noise_db:.1f} dB")
        print(f"  Avg residual SPL:     {avg_net_db:.1f} dB")
        print(f"  Average reduction:    {avg_noise_db - avg_net_db:+.1f} dB")
        print(f"  Peak noise SPL:       {peak_noise_db:.1f} dB")
        print(f"  Peak residual SPL:    {peak_net_db:.1f} dB")
        print(f"  Peak reduction:       {peak_noise_db - peak_net_db:+.1f} dB")
        print(f"{'=' * 50}\n")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="PIRL-ANC: Live simulation visualization",
    )
    parser.add_argument(
        "--checkpoint", default=None, type=str,
        help="Path to trained agent checkpoint (optional). "
             "Without this, runs with an untrained agent.",
    )
    parser.add_argument(
        "--config", default=None, type=str,
        help="Path to YAML config file (optional)",
    )
    parser.add_argument(
        "--interval", default=80, type=int,
        help="Animation interval in ms (default: 80)",
    )
    parser.add_argument(
        "--save", default=None, type=str,
        help="Save animation to file instead of displaying (e.g. demo.gif)",
    )
    args = parser.parse_args()

    run_live_demo(
        checkpoint=args.checkpoint,
        cfg_path=args.config,
        interval_ms=args.interval,
        save_path=args.save,
    )
